name: Build Threats

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Version Bump
        if: github.ref.type == 'tag'
        run: sed -Ei "s|<VersionPrefix>[0-9]*\.[0-9]*\.[0-9]*</VersionPrefix>|<VersionPrefix>${GITHUB_REF_NAME}</VersionPrefix>|g" Threats/Threats.csproj

      - name: Build
        run: dotnet build -c Release

      - name: Publish Win64
        run: dotnet publish Threats/Threats.csproj -c Release -o publish-win64 -r win-x64
      - name: Upload Win64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Threats-win64
          path: publish-win64

      - name: Publish Linux64
        run: dotnet publish Threats/Threats.csproj -c Release -o publish-linux64 -r linux-x64
      - name: Upload Linux64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Threats-linux64
          path: publish-linux64
