name: Continuous Integration
on:
  push:
    branches:
      - build
  workflow_dispatch:
jobs:
  build-windows:
    name: Build Windows x64
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build -c Release
      - name: Publish
        run: dotnet publish Threats/Threats.csproj -c Release -o publish -r win-x64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Threats.win-x64
          path: publish
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build -c Release
      - name: Publish
        run: dotnet publish Threats/Threats.csproj -c Release -o publish -r linux-x64
      - name: Packing Program
        run: tar -cvf Threats.linux-x64.tar publish/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Threats.linux-x64
          path: Threats.linux-x64.tar