name: Build Docs

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: List files
        id: list_files
        run: echo "files=$(printf '"%s" ' docs/*.md)" > $GITHUB_OUTPUT

      - name: Pandoc build
        uses: docker://pandoc/core:latest
        with:
          args:
            -s
            --metadata-file docs/meta.yml
            --resource-path=docs/
            -F pandoc-crossref
            --citeproc --csl=docs/templates/gost.csl
            --bibliography=docs/bibliography.bib
            --lua-filter=docs/filters/latin-italic.lua
            --toc
            --reference-doc=docs/templates/PZ.docx
            --output=Threats.docx
            ${{ steps.list_files.outputs.files }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Docs
          path: Threats.docx
